### PR TITLE
update to vexflow beta

### PR DESCRIPTION
**Pull request by rvilarl**
@jaredjj3 please help me fixing the error.
```
  [RuntimeError] NoStave: No stave attached to instance.

      77 |   @util.memoize()
      78 |   getWidth(): number {
    > 79 |     return this.getVfKeySignature().getWidth() + KEY_SIGNATURE_PADDING;
```

We need to set the stave before calling getWidth but I do not know how to get access to the stave in keysignature.ts

```
/** Returns the width of the key signature. */
  @util.memoize()
  getWidth(): number {
    return this.getVfKeySignature().getWidth() + KEY_SIGNATURE_PADDING;
  }
```

### CODE REVIEW

**Comment by jaredjj3** [comment]
I'm on mobile, apologies for the lack of formatting. Hopefully this unblocks you.

Right now, vexflow.Stave objects are created downstream in rendering.Part.getStaves. Some possible options:

- Create a temporary vexflow.Stave solely for measuring width. 
- Create vexflow.Stave objects in rendering.StaveSignature and pass it accordingly to rendering.KeySignature.

**Comment by rvilarl** [comment]
Thanks! I am considering if it makes sense to have the stave. This is required to calculate the bounding box position correctly but not the height and width.

**Comment by jaredjj3** [comment]
In keysignature.ts, this seemed to fix it:

```ts
  private getVfKeySignature(): vexflow.KeySignature {
    const vfStave = new vexflow.Stave(0, 0, 0);
    const vfKeySignature = new vexflow.KeySignature(
      this.getKey(),
      this.previousKeySignature?.getKey() ?? undefined,
      this.getAlterations()
    ).setPosition(vexflow.StaveModifierPosition.BEGIN);
    vfKeySignature.addToStave(vfStave);
    return vfKeySignature;
  }
```

However, I've been having issues running the test via `yarn test` (Docker) and `yarn jest`. The test setup probably needs to be updated.

**Comment by jaredjj3** [comment]
I was able to run the tests. The change I mentioned does produce diffs, but they're negligible.

**Comment by rvilarl** [comment]
I have set a PR in vexflow to avoid changes here.

**Comment by jaredjj3** [comment]
Thanks! I think that's a better solution since it will prevent other vexflow users from breaking.

**Comment by jaredjj3** [comment]
@rvilarl, I'm preparing to have this ready for VexFlow 5's release. Feel free to reach out to me when the issue we talked about has been addressed in VexFlow.

**Comment by jaredjj3** [comment]
@rvilarl, just FYI, I did this work in https://github.com/stringsync/vexml/pull/256.

**Comment by rvilarl** [comment]
@ronyeh could you release a beta?

**Comment by rvilarl** [comment]
@jaredjj3 this should be fixed in the vexflow 5.0.0-beta.1
your work around code should not be needed.

**Comment by jaredjj3** [comment]
@rvilarl removed in #275. Thanks!

**Pull request closed without merging**
