### PR TITLE
notations & beam refactored

### PR DESCRIPTION
**Pull request by rvilarl**
A lot of progress with notations, I have also refactored to reduce the number of messages.

image

### CODE REVIEW

**Review by jaredjj3 — APPROVED** [review]
Thanks for cleaning up these features. I'm glad you were able to simplify things a little bit. Do you think we're at a point where we can start writing unit tests and rethink the overarching approach?

**Comment by rvilarl** [comment]
Yes we should. From an overarching perspective we definitively need some structure otherwise the renderer will be a mess. I thought that the plan was to base the testing on the snapshots and the unofficial tests.

**Comment by jaredjj3** [comment]
>I thought that the plan was to base the testing on the snapshots and the unofficial tests.

I'll defer to your judgment if this is the best thing to do since the core library is mostly your work.

We can continue to do that, but the way we've been working can really only support one developer working on it (or otherwise we face merge conflict hell). You've built up a lot of momentum developing the core library, and now that we have something tangible, `vexml` might be easier to "sell" as a real possible MusicXML -> Vexflow solution and get more developers on board. Personally, I'd like the library to be in a place where more than one developer can work on it, but I don't really have a good sense of how far we are from that.

>I am very happy because I am detecting a lot of issues in VexFlow with this. 🙂

I'm genuinely happy to hear this. This is one of the things that I love about open-source software. I also think this is an avenue where we could get more support on this library.

**Comment by rvilarl** [comment]
I am happy to get more structure to allow more people to cooperate. What would you suggest?

**Pull request merged**
