### PR TITLE
Render lilypond01c

### PR DESCRIPTION
**Pull request by jaredjj3**
This PR renders 01c-Pitches-NoVoiceElement.xml and adds lyric rendering to the pipeline.

## Divergences

- The `<time>` element is not provided in 01c-Pitches-NoVoiceElement.xml. The default time signature in `vexml` is 4/4 while `lilypond` seems to expect cut time.
- The `vexml` rendering lacks a verse number.
- The `vexml` rendering has a beginning barline.

## vexml

image

## lilypond

image

### CODE REVIEW

**Comment by jaredjj3** [comment]
This PR may take a little bit more time than lilypond10b in #104 because I need to add a lyric rendering capability.

**Comment by rvilarl** [comment]
@jaredjj3 this one is still a draft, no complete, right?

**Comment by jaredjj3** [comment]
Right, the current vexml rendering doesn't have the lyrics, so I'm adding support for that in this PR.

image

**Comment by jaredjj3** [comment]
@rvilarl, do you know why the lyrics render above the notes I attach them to in this [fiddle](https://jsfiddle.net/qhz7s6mu/8/)?

**Comment by jaredjj3** [comment]
I figured out how to render lyrics below the note, but they're not on the same horizontal plane ([fiddle](https://jsfiddle.net/84ow1at9/)). I'll deal with this later in the lyric-focused lilypond tests. For now, I think this is good enough.

**Pull request merged**
