### PR TITLE
Add more event support

### PR DESCRIPTION
**Pull request by jaredjj3**
This PR fixes #227 by adding a basic event system. It adds an overlay element, which makes the event behavior consistent between SVG and canvas. Without this, SVG elements would "steal" touchend and touchcancel. I decided to leave the event system very bare and simple for now. I'll try to revisit before 1.0.0.

### CODE REVIEW

**Comment by jaredjj3** [comment]
> > It offers a slight advantage when an accidental is rendered, but the same could be achieve with boxes. Take a look at how the circle is off-center for notes with accidentals:
> > image
> 
> Vexflow includes the accidentals, flags and other modifiers in the bounding box. Of course bounding boxes are sometimes too big. See third note.
> 
> image

@rvilarl let's continue the conversation from https://github.com/stringsync/vexml/pull/230#issuecomment-2179813848 here.

I'm not getting the same result as the test. I'm using `vexflow.StaveNote.getBoundingBox`.

image

In the tests, I saw [something](https://github.com/0xfe/vexflow/blob/783af8671d6d5c6861ba80505b4cfa7834e30131/tests/stavenote_tests.ts#L104) dealing with `ModifierContext` that I'm not doing in vexml explicitly. I logged `vexflow.StaveNote.getModifierContext` and got this:

image

I suspect that this `ModifierContext` is incorrect. What's the correct way to use this so that the bounding box includes the modifiers?

**Comment by rvilarl** [comment]
To me the ModifierContext looks good: there is one Accidental and one StaveNote as expected.
What version of VexFlow are you using now? Are you adding the Modifiers to the notes?

**Comment by jaredjj3** [comment]
I'm using `vxflw-early-access 5.0.0-alpha.11` and I'm using `vexflow.StaveNote.addModifier` ([code](https://github.com/stringsync/vexml/blob/588b2191c0de1abf0c60c461d58c3743f8f865a2/src/rendering/note.ts#L265)).

**Comment by rvilarl** [comment]
> I'm using `vxflw-early-access 5.0.0-alpha.11` and I'm using `vexflow.StaveNote.addModifier` ([code](https://github.com/stringsync/vexml/blob/588b2191c0de1abf0c60c461d58c3743f8f865a2/src/rendering/note.ts#L265)).

@jaredjj3 please try with `vexflow 5.0.0-alpha.4` we do not release now in vxflw-early-access.

**Comment by rvilarl** [comment]
@jaredjj3 this is why I said that I had been working in BoundigBox. I resolved some problems but I expect more bugs. Let me know if you come across them.

**Comment by jaredjj3** [comment]
@rvilarl will do, thanks for improving it!

**Pull request merged**
