### PR TITLE
refactored to use System, vexflow included

### LINKED ISSUE #42: Chords
It is quite inconvenient that the chords have to be provided alphabeticaly ordered when this is not the case in Music XML. I am terying to resolve this in VexFlow but it by far more complicted than expected.
If I do not resolve that the processing of the chords' accidentals, ... will be very complicated.

### LINKED ISSUE #54: Passacaglia
@jaredjj3 I will now give support to `print` and make additional changes to make sure that passacaglia looks fine. We will see what comes out of this experiment. :)

### PR DESCRIPTION
**Pull request by rvilarl**
Hi @jaredjj3, I decided to include vexflow tgz to make progress.

Fixes #54 
Fixes #42

### CODE REVIEW

**Comment by rvilarl** [comment]
I hope you like it. We will also have to decide now what to do next? Suggestions?

**Comment by jaredjj3** [comment]
Great! I'll take a look this weekend.

**Comment by rvilarl** [comment]
> I hope you like it. We will also have to decide now what to do next? Suggestions?

I have open some issues with missing features. My suggestions on what to do next.

**Comment by jaredjj3** [comment]
I'm happy to see the deleted code, LGTM :)

Continuing to hunt down the missing features is the right move here. When we have enough of them done, maybe we can think about how everything is architected. But for now, let's keep implementing features.

**Review by jaredjj3 — APPROVED** [review]

**Pull request merged**
