### PR TITLE
LyricMessage support

### PR DESCRIPTION
**Pull request by rvilarl**
Basic support for lyrics. Yo will see that in 32a-Notations there are no overlaps

32a-Notations
-

### CODE REVIEW

**Comment by rvilarl** [comment]
About #51 I believe that someone might want to print a score without lyrics (instrumental only) and without having to edit the musicxml file.

**Comment by jaredjj3** [comment]
Awesome work! That looks good. I'll review shortly.

As far as configuration goes, I think we should only allow configuring things that MusicXML can't accomplish. A parallel is `opensheetmusicdisplay's` [EngravingRules](https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/blob/69ff4a62f4a2c487cfb91aed46eec5b617b5749e/src/MusicalScore/Graphical/EngravingRules.ts) class, but I believe this actually clashes with the MusicXML spec. I had a hard time using this and deciding whether or not to make a change in MusicXML or in the engraving rules.

I think we should push that complexity on the user, since the concern of excluding some notations belongs to the MusicXML document in my opinion. Knowing that the MusicXML spec is very complex, we can allow users to imperatively filter messages by adding an option to `RendererOptions`:

```ts
type RendererOptions = {
  codeTracker?: CodeTracker;
  UNSAFE_shouldProcessMessage?: (message: EasyScoreMessage) => boolean;
};
```

I think that's along the lines of what you originally proposed.

**Review by jaredjj3 — APPROVED** [review]
This PR being simpler is a good sign we're headed in the right direction. :)

**Comment by jaredjj3** [comment]
Actually, I like this better:

```ts
type RendererOptions = {
  codeTracker?: CodeTracker;
  UNSAFE_transformMessage?: (message: EasyScoreMessage, ctx: any) => EasyScoreMessage[] | EasyScoreMessage | null;
};
```

**Pull request merged**
