### PR TITLE
Render lilypond14a

### LINKED ISSUE #187: [BUG] (v0.0.0): Lilypond 14a does not render
**Expected behavior**
I expected 14a-StaffDetails-LineChanges.xml to render

image

**Actual behavior**
It throws the following error:

>17:24:09.678 (1296px) Error: Could not find stave signature for part P1 at https://vexml.dev/assets/index-lcbJYKa5.js:60:1236904 at Array.map (<anonymous>) at Cw.getParts (https://vexml.dev/assets/index-lcbJYKa5.js:60:1236734) at i.value (https://vexml.dev/assets/index-lcbJYKa5.js:49:3314) at Cw.getMultiRestCount (https://vexml.dev/assets/index-lcbJYKa5.js:60:1234919) at https://vexml.dev/assets/index-lcbJYKa5.js:60:1242079 at Array.map (<anonymous>) at bw.getMultiRestCount (https://vexml.dev/assets/index-lcbJYKa5.js:60:1242070) at Gh.getMeasures (https://vexml.dev/assets/index-lcbJYKa5.js:61:3359) at Gh.split (https://vexml.dev/assets/index-lcbJYKa5.js:61:1913)

**Screenshot**
N/A

**Hints**

It seems to be coming from https://github.com/stringsync/vexml/blob/ef071b8f0467dc08ccc283a2d0526d88bd6424b2/src/rendering/measurefragment.ts#L232C26-L232C35

- [X] Attach the MusicXML file used to produce the bug.
- [X] Attach the error messages.
- [X] Include any `vexml` code references where the bug may be.

### PR DESCRIPTION
**Pull request by jaredjj3**
This PR fixes #187 and #191.

Stave line _changes_ don't seem to be important to support since I assume most MusicXML compatible software does not allow it. However it is important that we support a single stave line for percussive notations.

## Divergences

- `lilypond` does not re-render the clef when the stave line count changes.
- `vexml` only renders the clef and time signature as if there were 5 stave lines.
- `osmd` and MuseScore4 both seem to only honor the last stave line specification.
- Guitar Pro 7 ignores Part 2 as well as the stave line specification.

## lilypond

image

## vexml

image

## osmd

image

## MuseScore4

image

## Guitar Pro 7

image

### CODE REVIEW

**Comment by jaredjj3** [comment]
The bug was that Part 1 had a measure fragment with no measure entries in it, while Part 2 did. With the current logic, stave signatures are conditionally added if there are measure entries _for a given part_. However, we need to consider all parts when deciding whether or not a stave signature should be added.

image

The only thing left to do is to honor the number of stave lines specified in MusicXML. The heavy lifting should already be done by the measure fragmentation.

Desired result:

image

**Comment by jaredjj3** [comment]
@rvilarl, I got an interesting result setting [vexflow.StaveOptions.numLines](https://github.com/0xfe/vexflow/blob/7e7eb97bf1580a31171302b3bd8165f057b692ba/src/stave.ts#L36):

vexml_dev_0_0_0 (7)

The clef and time signature behave as if the stave line was the 3rd from the top. Are these stave modifier placements expected?

**Comment by jaredjj3** [comment]
I'm not sure why the screenshots I'm producing in Docker are not reproducible when running on GitHub Actions. I'm going to figure this out before merging this PR.

**Comment by jaredjj3** [comment]
I just ran the tests on an x86 machine and there are no screenshot changes to be made.

**Comment by jaredjj3** [comment]
There must be a very subtle test dependency issue. I can reproduce the error locally running

```sh
yarn test integration/vexml 
```

but I don't get the error running

```sh
yarn test integration/vexml -t multi_system_spanners
```

**Comment by jaredjj3** [comment]
This is what the diff looks like:

multi_system_spanners_400px-diff

**Comment by jaredjj3** [comment]
I think it must've been some git issue. After I force pushed my branch, it seems to have started to recognize my snapshot changes.

**Comment by jaredjj3** [comment]
> @rvilarl, I got an interesting result setting [vexflow.StaveOptions.numLines](https://github.com/0xfe/vexflow/blob/7e7eb97bf1580a31171302b3bd8165f057b692ba/src/stave.ts#L36):
> 
> image
> The clef and time signature behave as if the stave line was the 3rd from the top. Are these stave modifier placements expected?

@rvilarl feel free to respond whenever you can. I'm going to merge this code so I can work on the other issue you raised.

**Comment by rvilarl** [comment]
> > @rvilarl, I got an interesting result setting [vexflow.StaveOptions.numLines](https://github.com/0xfe/vexflow/blob/7e7eb97bf1580a31171302b3bd8165f057b692ba/src/stave.ts#L36):
> > image
> > The clef and time signature behave as if the stave line was the 3rd from the top. Are these stave modifier placements expected?
> 
> @rvilarl feel free to respond whenever you can. I'm going to merge this code so I can work on the other issue you raised.

@jaredjj3 I am trying to see how this works. I do not know. I cannot see the image.

**Comment by rvilarl** [comment]
> @rvilarl, I got an interesting result setting [vexflow.StaveOptions.numLines](https://github.com/0xfe/vexflow/blob/7e7eb97bf1580a31171302b3bd8165f057b692ba/src/stave.ts#L36):
> 
> image
> The clef and time signature behave as if the stave line was the 3rd from the top. Are these stave modifier placements expected?

@jaredjj3 Yes, this is expected. Would `lineConfig = [false, false, true, false, false]` help?

**Comment by jaredjj3** [comment]
Yes, that would allow me to achieve the lilypond result and I think it's flexibility you'd want in vexflow. Thanks for double checking me!

Also consider a number[], where the numbers are the indexes where to draw lines. However, with what you proposed, there's less validation you'd have to do on the input. Either signature works for me.

**Comment by rvilarl** [comment]
Happy new year!

**Comment by jaredjj3** [comment]
Thanks to you as well! I appreciate all the help you've given me on this library. I wouldn't have gotten this far without your help!

**Pull request merged**
