### PR TITLE
Gladiolus Rag fixes

### PR DESCRIPTION
**Pull request by jaredjj3**
This PR addresses some issues rendering Gladiolus Rag by Joplin in #78, but does not completely fix it.

- [x] Ensure that the top of a rendering is present.
- [x] Prevent ties from rendering across systems.
- [x] Investigate increasing `StaveTie` height, part distance, or both.
- [x] Render repeats.

This PR adds basic support for rendering repeat barlines. I'll address alternative endings in lilypond 45b-RepeatWithAlternatives.xml.

## Before

vexml_dev_0_0_0 (1)

## After

vexml_dev_0_0_0

### CODE REVIEW

**Comment by rvilarl** [comment]
wow! This looks so good!

**Comment by rvilarl** [comment]
The cross tab elements are missing.

image

**Comment by jaredjj3** [comment]
Thanks for calling this out — this part is very tricky. The next step is to make a small [vexml integration test case](https://github.com/stringsync/vexml/tree/master/tests/integration/__data__/vexml) reproducing that.

I have a theory on what's broken.

Beams assume that they will see all their notes before starting another beam. I know this because they are not [keyed](https://github.com/stringsync/vexml/blob/f7b839a0596cef76a106df48e55274d86cfae35a/src/rendering/beam.ts#L26) by anything in their underlying `SpannerMap`. There's currently no mechanism to have multiple beams open at the same time.

So far, I can think of doing one of the following solutions:

1. Figure out a key for the beam's `SpannerMap`. Maybe we can infer one from the note's [Address](https://github.com/stringsync/vexml/blob/master/src/rendering/address.ts). The thing is that I'd have to be very careful with further assumptions about beams (e.g. can beams traverse measure boundaries?).
2. When providing `SpannerData` ([code](https://github.com/stringsync/vexml/blob/f7b839a0596cef76a106df48e55274d86cfae35a/src/rendering/types.ts#L6)), include data from all staves. Then, `Beam` should be responsible for searching other staves for notes that also belong to a given beam opening.

**Comment by rvilarl** [comment]
I believed not, but...

image

**Comment by jaredjj3** [comment]
I'm glad you found this! Music notation is full of wonderful edge cases.

**Pull request merged**
