### PR TITLE
Render lilypond32a (fermatas)

### PR DESCRIPTION
**Pull request by jaredjj3**
This PR renders fermatas, which is part of lilypond32a.

## lilypond

image

## vexml

image

### CODE REVIEW

**Comment by jaredjj3** [comment]
Beat me to it — I was going to file a bug for this :)

I didn't see the corresponding [articulation in vexflow tables](https://github.com/0xfe/vexflow/blob/8ddc8fa1a6d304a879e73830919fa17f3a9bdef4/src/tables.ts#L468) nor the `vexflow` tests.

Next, I rendered lilypond32a in OSMD and saw that it's not supported there either. I came to the conclusion that it's not supported in `vexflow`.

image

**Comment by jaredjj3** [comment]
@rvilarl, I filed an issue for the angled and square fermatas at https://github.com/0xfe/vexflow/issues/1608.

**Comment by rvilarl** [comment]
@jaredjj3 I am pretty sure that they are supported im Vexflow 5 I will look into that

**Comment by rvilarl** [comment]
@jaredjj3 they are there :) The `fermataShortAbove/Below` are the angled ones and the `fermataLongAbove/Below` is the squared ones.

**Comment by rvilarl** [comment]
image

**Comment by jaredjj3** [comment]
I accidentally pushed directly to `master`, but I fixed it now. Thanks for your help @rvilarl!

image

**Pull request merged**
