### PR TITLE
Render lilypond11g

### PR DESCRIPTION
**Pull request by jaredjj3**
This PR renders 11g-TimeSignatures-SingleNumber.xml. It also adds support for `single-number` time signatures, which updated the snapshot for 11f-TimeSignatures-SymbolMeaning.xml.

## Divergences

The renderers here don't support this kind of time signature. `vexflow` doesn't support this either, but I think this is a good signal to accept this divergence.

## vexml

image

## lilypond

image

## osmd

image

## MuseScore 4

image

## GuitarPro 7

image

### CODE REVIEW

**Comment by rvilarl** [comment]
@jaredjj3 did you try?
```js
new Stave(10, 10, 300)
    .addTimeSignature('3');
  ```

**Comment by jaredjj3** [comment]
Hmm I thought I did. I’ll try again when I resume in a few hours or tomorrow.

**Comment by jaredjj3** [comment]
@rvilarl, this doesn't seem to work: https://jsfiddle.net/gynua7pv/3/. Am I doing something wrong?

**Comment by rvilarl** [comment]
I will look into that, it seems to be a vexflow problem.

**Pull request merged**
