### PR TITLE
Render lilypond01e

### PR DESCRIPTION
**Pull request by jaredjj3**
This PR renders 01e-Pitches-ParenthesizedAccidentals.xml.

## Divergences

- Measure 3 does not fit in `vexml`.
- In `lilypond`, I suspect they erroneously omit the accidental on the editorial-only note (the second note of each measure).
- In `osmd` and `gp7`, they seem to ignore accidentals when they are labeled cautionary OR editorial.

## vexml

image

## lilypond

image

## osmd

image

## gp7

image

### CODE REVIEW

**Comment by rvilarl** [comment]
@jaredjj3 what is gp7

**Comment by jaredjj3** [comment]
Guitar Pro 7

**Comment by rvilarl** [comment]
Thanks sorry for missing your question on lyrics, I am travelling.

**Comment by jaredjj3** [comment]
No worries, I'm not blocked. We can revisit how to render lyrics with vexflow in the `61*` lilypond tests :)

**Pull request merged**
